(() => {
  const session = () => JSON.parse(localStorage.getItem('codm-vault-users') || '[]').find(user => user.id === localStorage.getItem('codm-vault-session'));
  const toast = (message, kind = 'error') => { let box = document.getElementById('siteToast'); if (!box) { box = document.createElement('div'); box.id = 'siteToast'; document.body.append(box); } box.className = `site-toast ${kind}`; box.textContent = message; clearTimeout(box.dismiss); box.dismiss = setTimeout(() => box.classList.remove('show'), 4500); requestAnimationFrame(() => box.classList.add('show')); };
  const settingsKey = user => `codm-vault-settings-${user.id}`;
  const readSettings = user => JSON.parse(localStorage.getItem(settingsKey(user)) || '{}');
  const applySettings = user => { if (!user) return; const settings = readSettings(user); document.body.classList.toggle('plain-bg', settings.background === 'plain'); if (settings.color) document.body.style.setProperty('--user-bg-color', settings.color); if (settings.icon) document.querySelectorAll('.profile-trigger .avatar').forEach(item => item.textContent = settings.icon); };
  const showSettings = () => { const user = session(); if (!user) return; let modal = document.getElementById('settingsModal'); if (!modal) { modal = document.createElement('div'); modal.id = 'settingsModal'; modal.className = 'settings-modal'; modal.innerHTML = `<div class="settings-panel"><button class="settings-close" type="button">x</button><p class="eyebrow">PROFILE SETTINGS</p><h2>Make it yours</h2><label for="settingsName">Profile name</label><input id="settingsName" maxlength="24"><label for="settingsIcon">Profile icon</label><input id="settingsIcon" maxlength="2" placeholder="A"><label for="settingsBackground">Background</label><select id="settingsBackground"><option value="image">Mode image</option><option value="plain">Plain colour</option></select><label for="settingsColor">Plain colour</label><input id="settingsColor" type="color" value="#172021"><button class="button primary" id="saveSettings" type="button">Save changes</button></div>`; document.body.append(modal); modal.querySelector('.settings-close').onclick = () => modal.classList.remove('open'); modal.onclick = event => { if (event.target === modal) modal.classList.remove('open'); }; modal.querySelector('#saveSettings').onclick = () => { const settings = { profileName: modal.querySelector('#settingsName').value.trim() || user.username, icon: modal.querySelector('#settingsIcon').value.trim().slice(0, 2).toUpperCase() || user.username[0].toUpperCase(), background: modal.querySelector('#settingsBackground').value, color: modal.querySelector('#settingsColor').value }; const users = JSON.parse(localStorage.getItem('codm-vault-users') || '[]').map(item => item.id === user.id ? { ...item, profileName: settings.profileName } : item); localStorage.setItem('codm-vault-users', JSON.stringify(users)); localStorage.setItem(settingsKey(user), JSON.stringify(settings)); modal.classList.remove('open'); applySettings({ ...user, profileName: settings.profileName }); const label = document.getElementById('profileLabel'); if (label) label.textContent = settings.profileName; toast('Profile settings saved.', 'success'); }; } const settings = readSettings(user); modal.querySelector('#settingsName').value = settings.profileName || user.profileName || user.username; modal.querySelector('#settingsIcon').value = settings.icon || user.username[0]; modal.querySelector('#settingsBackground').value = settings.background || 'image'; modal.querySelector('#settingsColor').value = settings.color || '#172021'; modal.classList.add('open'); };
  document.addEventListener('click', event => { if (event.target.id !== 'loginSubmit') return; event.preventDefault(); event.stopImmediatePropagation(); const now = Date.now(), lock = JSON.parse(localStorage.getItem('codm-vault-login-lock') || '{}'); if (lock.until > now) { toast(`Too many attempts. Try again in ${Math.ceil((lock.until - now) / 1000)} seconds.`); return; } const gate = document.getElementById('authGate'), id = gate.querySelector('#loginId').value.trim().toLowerCase(), password = gate.querySelector('#loginPassword').value, users = JSON.parse(localStorage.getItem('codm-vault-users') || '[]'), found = users.find(user => (user.email === id || user.username === id) && user.password === password); if (found) { localStorage.removeItem('codm-vault-login-lock'); localStorage.setItem('codm-vault-session', found.id); location.reload(); return; } const attempts = (lock.attempts || 0) + 1; if (attempts >= 5) { localStorage.setItem('codm-vault-login-lock', JSON.stringify({ attempts: 0, until: now + 30000 })); toast('Five failed attempts. Login is paused for 30 seconds.'); } else { localStorage.setItem('codm-vault-login-lock', JSON.stringify({ attempts, until: 0 })); toast(`Incorrect email, username, or password. Attempt ${attempts} of 5.`); } }, true);
  const setup = () => { applySettings(session()); const settingsButton = document.getElementById('settingsButton'); if (settingsButton) settingsButton.onclick = showSettings; };
  setup();
})();
